"""add datetime

Revision ID: 2c1e62f25e12
Revises: d0107b64a60f
Create Date: 2022-05-11 16:23:58.277331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1e62f25e12'
down_revision = 'd0107b64a60f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'posted')
    # ### end Alembic commands ###
