"""adding changes to upvote and downvote

Revision ID: d0107b64a60f
Revises: 773c607ae25f
Create Date: 2022-05-11 13:16:40.515449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0107b64a60f'
down_revision = '773c607ae25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitch_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('comments', 'pitch')
    op.add_column('downvotes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'downvotes', 'users', ['user_id'], ['id'])
    op.add_column('upvotes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_column('upvotes', 'user_id')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_column('downvotes', 'user_id')
    op.add_column('comments', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitch_fkey', 'comments', 'pitches', ['pitch'], ['id'])
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
